### PR TITLE
pypi ready

### PR DESCRIPTION
**Pull request by emphasize**
Let's get this one rolling

- autotranslated
- tests for
    - osm
    - skill behaviour (loader, intents, featured media, search)
- workflows

### CODE REVIEW

**Comment by emphasize** [comment]
Few things about failing tests i found:
First off, package tunein has to be bumped to .3 (that has to be reflected in requirements.txt)
Regarding to that i found that 0.0.3a1 of said package points to a earlier commit ([commit not included](https://github.com/OpenJarbas/tunein/commit/a66bedb0b081fc8ffaedd322840ebc7d962c409a))

**Comment by mikejgray** [comment]
Installed on RaspOVOS and Neon Mark 2, cannot get it to play with either test intent in the README. Removed conflicting SomaFM skill, same results.

**Comment by emphasize** [comment]
Stated above it would need tunein to get a bump or manually adding https://github.com/OpenJarbas/tunein/commit/a66bedb0b081fc8ffaedd322840ebc7d962c409a

**Comment by emphasize** [comment]
But good call, the examples are somewhat BS with this skill (seems copy/paste). Your asking for a radio station.
`Heavy Metal` [query](https://tunein.com/search/?query=heavy%20metal) would bring up stations, but we should show a station example rather than a genre

**Review by JarbasAl — APPROVED** [review]

**Comment by emphasize** [comment]
get the same generator exception, but it ultimately plays the station. Will investigate

**Comment by goldyfruit** [comment]
> For the -not skill related- looping situation, @JarbasAl pls have a look at [this log](https://paste.api-zulu.com/?ae1ba80846c0c78e#4rskZbyp96LPJWxsBNzV9MboZDnJ4TbBJDQDFpftXKpr) and [this log](https://paste.api-zulu.com/?ba4c98982d9c3659#2ccWJnqGR5hLKzjoVBdvun3v9TN6dg1kwz3vzU2mRPaB) can`t decipher what is happening there

Can't stop the loop xD

**Comment by goldyfruit** [comment]
With the latest `tunein` release I don't get the trace anymore, but still loop in audio and not music.

**Comment by emphasize** [comment]
This is not skill related, so should be discussed elsewhere

**Review by goldyfruit — APPROVED** [review]

**Pull request merged**
